# Generated by Django 2.2.1 on 2019-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0004_remove_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='gener',
            field=models.ManyToManyField(to='mdb_app.Gener'),
        ),
    ]
