# Generated by Django 2.2.1 on 2019-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb_app', '0005_auto_20190511_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gener',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
